services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['console.command']

  app.command.create_events:
    class: App\Command\CreateEventsOnContentfulCommand
    arguments:
      - '%env(CONTENTFUL_MASTER_SPACE_ID)%'
      - '@app.contentful.delivery.main_client'
      - '@app.contentful.entry_factory'

  app.command.delete_events:
    class: App\Command\DeleteEventsOnContentfulCommand
    arguments:
      - '%env(CONTENTFUL_MASTER_SPACE_ID)%'
      - '@app.contentful.delivery.main_client'

  app.command.syncronyze_google_calendar:
    class: App\Command\CreateEventsOnGoogleCalendarCommand
    arguments:
      - '@app.contentful.delivery.main_client'
      - '%env(CONTENTFUL_MASTER_SPACE_ID)%'
      - '@translator'
      - '@router.default'
      - '@app.repository.event'
      - '@app.service.google_calendar_event_factory'
      - '@app.service.google_calendar_service_factory'
      - '%env(GOOGLE_CALENDAR_ID)%'