services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['console.command']

  app.command.create_events:
    class: App\Command\CreateEventsOnContentfulCommand
    arguments:
      - '@app.repository.event'
      - '@app.contentful.entry_factory'

  app.command.delete_events:
    class: App\Command\DeleteEventsOnContentfulCommand
    arguments:
      - '@app.repository.event'

  app.command.syncronyze_google_calendar:
    class: App\Command\CreateEventsOnGoogleCalendarCommand
    arguments:
      - '@app.repository.google_calendar_event'
      - '@app.repository.event'
