services:
  _defaults:
    autowire: true # see https://github.com/symfony/symfony/issues/36495
    autoconfigure: false
    public: true

  _instanceof:
    Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
      tags: ['controller.service_arguments']

  app.controller.cms_page:
    class: App\Controller\CmsPage
    arguments:
      - '@app.repository.cms_page'
      - '@app.service.breadcrumbs'

  app.controller.contact:
    class: App\Controller\Contact
    arguments:
      - '@app.service.breadcrumbs'
      - '@app.repository.cms_page'
      - '@mailer'
      - '@translator'
      - '%no_replay_mail%'
      - '%env(PARISH_REGISTRY_MAIL)%'

  app.controller.forms:
    class: App\Controller\Forms
    arguments:
      - '@app.repository.form'
      - '@app.service.breadcrumbs'

  app.controller.homepage:
    class: App\Controller\Homepage
    arguments:
      - '@app.repository.news'
      - '@app.repository.event'
      - '@contentful.delivery.client'

  app.controller.news:
    class: App\Controller\News
    arguments:
      - '@app.repository.news'
      - '@app.service.breadcrumbs'

  app.controller.header:
    class: App\Controller\Header
    arguments:
      - '@serializer.encoder.json'
      - '@app.service.breadcrumbs'

  app.controller.footer:
    class: App\Controller\Footer
    arguments:
      - '@serializer.encoder.json'
      - '@app.service.breadcrumbs'

  app.controller.informative:
    class: App\Controller\Informative
    arguments:
      - '@app.repository.informative_page'
      - '@app.service.breadcrumbs'

  app.controller.web_hook_delete_event:
    class: App\Controller\DeleteGoogleCalendarEventWebHook
    arguments:
      - '@app.repository.google_calendar_event'
      - '%env(WEBHOOK_SECRET_TOKEN_VALUE)%'

  app.controller.calendar:
    class: App\Controller\Calendar
    arguments:
      - '@app.service.breadcrumbs'

  app.controller.web_hook_save_event:
    class: App\Controller\SaveGoogleCalendarEventWebHook
    arguments:
      - '@app.repository.event'
      - '%env(WEBHOOK_SECRET_TOKEN_VALUE)%'
      - '@app.repository.google_calendar_event'