services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  app.repository.cms_page:
    class: App\Repository\CmsPageRepository
    arguments:
      - '@contentful.delivery.client'
      - '@app.contentful.query_factory'

  app.repository.form:
    class: App\Repository\FormRepository
    arguments:
      - '@contentful.delivery.client'
      - '@app.contentful.query_factory'

  app.repository.news:
    class: App\Repository\NewsRepository
    arguments:
      - '@contentful.delivery.client'
      - '@app.contentful.query_factory'

  app.repository.event:
    class: App\Repository\EventRepository
    arguments:
      - '@contentful.delivery.client'
      - '@app.contentful.query_factory'
      - '%env(CONTENTFUL_SPACE_ID)%'
      - '@app.contentful.management_client'

  app.repository.informative_page:
    class: App\Repository\InformativePageRepository
    arguments:
      - '@contentful.delivery.client'
      - '@app.contentful.query_factory'

  app.repository.google_calendar_event:
    class: App\Repository\GoogleEventCalendarRepository
    arguments:
      - '@app.service.event_id_resolver'
      - '@app.service.google_calendar_service_factory'
      - '%env(GOOGLE_CALENDAR_ID)%'
      - '@app.service.google_calendar_event_factory'
      - '@router'
      - '@translator'