services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  app.repository.cms_page:
    class: App\Repository\CmsPageRepository
    arguments:
      - '@contentful.delivery.client'
      - '@app.contentful.query_factory'

  app.repository.form:
    class: App\Repository\FormRepository
    arguments:
      - '@contentful.delivery.client'
      - '@app.contentful.query_factory'

  app.repository.new:
    class: App\Repository\NewRepository
    arguments:
      - '@contentful.delivery.client'
      - '@app.contentful.query_factory'