homepage:
  path: /
  controller: \App\Controller\Homepage::index

news_listing:
  path: /notizie
  controller: \App\Controller\News::list

news_index:
  path: /notizia/{slug}
  controller: \App\Controller\News::index

forms_listing:
  path: /modulistica
  controller: \App\Controller\Forms::list