homepage:
  path: /
  controller: \App\Controller\Homepage::index

news_listing:
  path: /notizie
  controller: \App\Controller\News::list

news_index:
  path: /notizia/{slug}
  controller: \App\Controller\News::index

forms_listing:
  path: /moduli
  controller: \App\Controller\Forms::list

cms_page:
  path: /{slug}
  controller: \App\Controller\Cms::index