delete_google_calendar_event_webhook:
  path: /delete-google-calendar-event/{contenfulId}
  controller: app.controller.web_hook_delete_event::index

save_google_calendar_event_webhook:
  path: /save-google-calendar-event/{contenfulId}
  controller: app.controller.web_hook_save_event::index

header:
  path: /_header
  controller: app.controller.header::index

footer:
  path: /_footer
  controller: app.controller.footer::index

homepage:
  path: /
  controller: app.controller.homepage::index

news_listing:
  path: /notizie
  controller: app.controller.news::list

news_index:
  path: /notizia/{slug}
  controller: app.controller.news::index

forms_listing:
  path: /modulistica
  controller: app.controller.forms::list

contact_page:
  path: /contatti
  controller: app.controller.contact::index

informative_page:
  path: /informativa/{slug}
  controller: app.controller.informative::index

calendar_page:
  path: /calendario
  controller: app.controller.calendar::index

cms_page:
  path: /{slug}
  controller: app.controller.cms_page::index