imports:
  - resource: "services/*.yaml"

services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  app.service.breadcrumbs:
    class: App\Service\BreadcrumbsGetter
    arguments:
      - '@router.default'
      - '@translator'