imports:
  - resource: "services/*.yaml"

parameters:
  router.request_context.host: www.upreginadellafamiglia.it
  router.request_context.scheme: https
  no_replay_mail: 'nonrispondermi@upreginadellafamiglia.it'

services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  app.service.breadcrumbs:
    class: App\Service\BreadcrumbsGetter
    arguments:
      - '@router.default'
      - '@translator'

  app.service.google_calendar_service_factory:
    class: App\Service\GoogleCalendarServiceFactory
    arguments:
      - '%env(GOOGLE_CALENDAR_AUTHORIZATION_KEYS)%'

  app.service.google_calendar_event_factory:
    class: App\Service\GoogleCalendarEventFactory