imports:
  - resource: "services/*.yaml"

parameters:
  router.request_context.host: www.upreginadellafamiglia.it
  router.request_context.scheme: https
  no_replay_mail: 'nonrispondermi@upreginadellafamiglia.it'
  asset.request_context.secure: true

services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  app.service.breadcrumbs:
    class: App\Service\BreadcrumbsGetter
    arguments:
      - '@router'
      - '@translator'

  app.service.google_calendar_service_factory:
    class: App\Service\GoogleCalendarServiceFactory
    arguments:
      - '%env(GOOGLE_CALENDAR_AUTHORIZATION_KEYS)%'

  app.service.google_calendar_event_factory:
    class: App\Service\GoogleCalendarEventFactory

  app.service.event_id_resolver:
    class: App\Service\EventIdResolver
    arguments:
      - '%env(DATABASE_DSN)%'
      - '%env(DATABASE_USER)%'
      - '%env(DATABASE_PASSWORD)%'