name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    name: Build the artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install PHP dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
          version: 2
          command: |
            composer install -n --prefer-dist
            composer dump-autoload --optimize

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run build

      - name: Compress the artifact
        run: zip --symlinks -q -r build.zip . -x "./node_modules/*"

  deploy:
    name: Deploy to prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
      - name: Add hosts.yml
        run: echo '${{ secrets.HOSTS_YML }}' > $GITHUB_WORKSPACE/hosts.yml
      - name: Deploy
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy production -vvv